### ISSUE TITLE
Feature request: add support for slave dns

### ISSUE THREAD

**Issue by actatux** [bluebanquise/bluebanquise#100]
I was reviewing the `dns_client` and `dns_server` roles and noticed there is a maximum number of one DNS server per network.

Could we consider adding support for secondary DNS servers?
We can discuss this in this thread then I can push a PR if accepted.

**Comment by oxedions** [comment]
Dear @actatux ,

This is indeed a good question.

Yes, this would be very easy to add. Maybe I would suggest that instead of:

`dns_ip: 10.10.0.7`

Two syntax would be accepted, and the Jinja code would switch from one to the other without issues:

`dns_ip: 10.10.0.7`

or

```
dns_ip:
  - 10.10.0.7
  - 10.10.0.8
```

Allowing more than 2 DNS servers...

Using an "if" with "is iterable", maybe it would worth a try.

Ben

**Comment by actatux** [comment]
[Code is almost ready](https://github.com/actatux/bluebanquise/tree/feat/dns_server_slaves), sleeping since 2 months because I still need to test multiple icebergs.
Before going further, would this be implemented in dns_server role or in a new role advanced-dns_server?

**Comment by oxedions** [comment]
Sorry for delay. In core, no need to go to advanced-core. DNS can be more advanced, as /etc/hosts can do the trick for basic usage.
