### ISSUE TITLE
strange character in some roles: TASK [dhcp_server : template █ Generate /etc/dhcp/dhcpd.conf]

### ISSUE THREAD

**Issue by strus38** [bluebanquise/bluebanquise#399]
It seems that some role have some 'black' character. IS that on purpose? a '-' would be a better replacement, no?

```
TASK [time : firewalld █ "Add services to firewall's public zone"] *****************************************************
Monday 05 October 2020  09:32:48 +0000 (0:00:00.128)       0:01:50.338 ********
skipping: [management1] => (item=ntp)

TASK [time : package █ Install chrony packages] ************************************************************************
Monday 05 October 2020  09:32:48 +0000 (0:00:00.100)       0:01:50.439 ********
ok: [management1]

TASK [time : template █ Generate /etc/chrony.conf] *********************************************************************
Monday 05 October 2020  09:32:51 +0000 (0:00:02.367)       0:01:52.806 ********
changed: [management1]

etc...
```

**Comment by oxedions** [comment]
It is on purpose.

After some search, JK found that some "standard / recommendations / nice ways to do" for tasks naming is: type of module, then pipe |, then title.
Since sometime pipe is not easy to see, this Ascii character █ has been used as a replacement. Also, you can note that another character is present. The full one is for actions that do modifications on the system, while light one is for role internal mechanism that do not have any impact on the system. 🙂

**Comment by strus38** [comment]
ok, good to know.
