### ISSUE TITLE
Use privilege escalation: become

### ISSUE THREAD

**Issue by SckyzO** [bluebanquise/bluebanquise#507]
For security reasons it would be better to use privilege escalation: **become** rather than running playbooks as root

**Comment by btravouillon** [comment]
Hello @SckyzO ,

Thank you for your comment. The purpose of the stack is to provide Ansible roles. There are some examples of playbooks to help with the initial setup of a cluster of hosts, but we cannot cover all the use cases, nor the wide range of Ansible configuration, thus we use the easiest way to run playbooks to configure systems. Each sysadmin has to leverage to possibilities of Ansible to fulfill the needs of their organization.

I will convert this issue to a discussion though, because this can be useful to discuss this further with other users of our community. If some consensus is found on how one could implement security in their IT, we could consider adding a chapter about this in the documentation.
