### ISSUE TITLE
[BUG] atftp downloading NBP file very slow

### ISSUE THREAD

**Issue by sgaosdgr** [bluebanquise/bluebanquise#854]
During a compute node installation, download ipxe file is very slow.  The boot process displays "Downing a NBD file ...." and got  stuck for over 10 minutes. Eventually the pxe menu comes up. 

## Context

It takes about 10 minutes to download ipxe image files during a node PXE installation.  The process is stuck at "Downloading a NBD file ....". 

Manually replaced atftp with tftp-server.  The slow download issue does not exist with tftp-server. 

## Process

1. Configure bond0 interface (two 10GigE NICs) for PXE/network installation
2. Boot up a compute node from network
3. Watch the network boot process (very slow)
4. Manually remove atftp and install tftp-server and start tftp-server daemon
5. Repeat step 2, 3.  With tftp-server, download speed is significantly faster

## Expected result

PXE booting a compute node should be fast and PXE menu should show up very quickly

## Current result

PXE booting a compute node is very slow and it takes about 10 minutes before PXE menu shows up

## Possible Fix

1. Tune atftp to work with bond0 interface (of two 10GigE NICs) so there is no any noticeable delay for downloading boot image files
2. Replace atftp with OS stock tftp server package. For RockyLinux, it's tftp-server.

**Comment by oxedions** [comment]
Thank you for opening this issue. :blush: 

Hum, this is strange. In normal time, tftp-server from RHEL is known to be slow and atftp to be much able to scale.

I will investigate, maybe recent versions of atftp have a known issue. I may try to build a newer version.

In the mean-time, would you accept to check if your system is able to fully boot over http, i.e. do not use TFTP at all ?

To do so, edit manually the dhcp configuration file, and instead of something like:

```
filename "x86/standard_snponly_ipxe.efi";
```

Replace by:

```
filename "http://yourserverip/standard_snponly_ipxe.efi";
```

And restart the dhcp server.
Then copy iPXE rom from `/var/lib/tftpboot/x86_64` to `/var/www/html` and have the node boot on its dual 10Gb in LACP.

You can watch httpd logs by opening a shell on the server with this listening:

```
tail -f /var/log/httpd/*
```

If this solves your issue, I will add the possibility to choose between http or tftp for boot (its a very easy dev and I had to do it for a long time). Tftp is mainly for compatibility purpose, but all moderns equipment can now boot over http.

Another solution is to use the facebook tftp server. I made a small tutorial here on how to use it: http://bluebanquise.com/tutorials/sysadmin_servers_farm_deployment/#pxe-stack

**Comment by sgaosdgr** [comment]
I will give http a try sometime this week.

**Comment by oxedions** [comment]
I also see that there is a newer version of atftp: https://sourceforge.net/projects/atftp/files/
I currently build 0.7.5 https://github.com/bluebanquise/infrastructure/blob/master/packages/atftp/version.sh

I do not know how the 8.0.0 version behave, maybe it could worth a try too. I lack hardware to test it to be honest, in my VMs its fast with a single link, and I cannot reproduce the 10Gb LACP configuration.

**Comment by sgaosdgr** [comment]
Tried setting up boot to http, but current dhcp configuration does not support http boot well.

It falls back to atftp service with following error:
```
Jan 24 15:08:17 mgt1 atftpd[205027]: Serving http://10.10.6.1/ipxe/standard_default_ipxe.efi to 10.10.6.249:1836
Jan 24 15:08:17 mgt1 atftpd[205027]: File /var/lib/tftpboot/http://10.10.6.1/ipxe/standard_default_ipxe.efi not found
```

Revered the temporary change and go back to boot to pxe. System logged following entries:
```
Jan 24 15:14:20 mgt1 dhcpd[215565]: DHCPREQUEST for 10.10.6.249 (10.10.6.1) from 40:a6:b7:95:82:60 via bond0 
Jan 24 15:14:20 mgt1 dhcpd[215565]: DHCPACK on 10.10.6.249 to 40:a6:b7:95:82:60 via bond0 
Jan 24 15:14:20 mgt1 atftpd[205027]: socket may listen on any address, including broadcast
Jan 24 15:14:20 mgt1 atftpd[205027]: Serving x86_64/standard_default_ipxe.efi to 10.10.6.249:1598
Jan 24 15:14:20 mgt1 atftpd[205027]: tsize option -> 1090048
Jan 24 15:14:20 mgt1 atftpd[205027]: blksize option -> 1468
Jan 24 15:14:20 mgt1 atftpd[205027]: Server thread exiting
Jan 24 15:14:20 mgt1 atftpd[205027]: socket may listen on any address, including broadcast
Jan 24 15:14:20 mgt1 atftpd[205027]: Serving x86_64/standard_default_ipxe.efi to 10.10.6.249:1599
Jan 24 15:14:20 mgt1 atftpd[205027]: blksize option -> 1468
Jan 24 15:27:02 mgt1 atftpd[205027]: Server thread exiting
Jan 24 15:27:04 mgt1 atftpd[205027]: socket may listen on any address, including broadcast
Jan 24 15:27:04 mgt1 atftpd[205027]: Serving x86_64/autoexec.ipxe to 10.10.6.249:1600
Jan 24 15:27:04 mgt1 atftpd[205027]: File /var/lib/tftpboot/x86_64/autoexec.ipxe not found 
Jan 24 15:27:04 mgt1 atftpd[205027]: Server thread exiting
```

Maybe the slow NBP downloading is due to missing /var/lib/tftpboot/x86_64/autoexec.ipxe?

**Comment by oxedions** [comment]
Dear @sgaosdgr 

I tried using the following syntax:

```
  host mgt9-net-admin-mac {
    option host-name "mgt9";
    hardware ethernet 1a:2b:3c:4d:9e:8f;
    fixed-address 10.10.0.9;
    filename "http://10.10.0.1/toto.kpxe";
  }
```

And it booted over http.

```
10.10.0.9 - - [25/Jan/2024:09:43:23 +0000] "GET /toto.kpxe HTTP/1.1" 200 97432 "-" "iPXE/1.21.1+git-20220113.fbbdc3926-0ubuntu1"
```

I will check if I can find an EFI system to check on EFI, my VMs are using legacy boot.

**Comment by oxedions** [comment]
Indeed, in EFI this doesn't work. I will investigate :blush:

**Comment by oxedions** [comment]
Ok, here is the solution.

UEFI recent hardware is able to choose between ipv4 PXE or ipv4 HTTP PXE. You can choose between both in the BIOS.
Solution is to go with an http url, like you did, but asking the BIOS to boot over UEFI HTTP natively.

For example on this bios screenshot I found on the web:

![image](https://github.com/bluebanquise/bluebanquise/assets/15154435/22a8472a-e99a-46d7-ab28-3cf192468cc7)

You can see there is a choice between legacy PXE (this one uses TFTP) or HTTP PXE (this one is using http). I tested it into a VM and it works.

As a reminder, you also need to disable secureboot if you use this feature. With libvirt, instead of a simple `--boot=uefi` I had to use `--boot firmware=efi,firmware.feature0.enabled=no,firmware.feature0.name=secure-boot` (found here https://www.mail-archive.com/virt-tools-list@redhat.com/msg16957.html)

If this UEFI HTTP boot matches your need, I will adapt the dhcp role to simply allow such feature by automatically sorting if client is HTTP able or legacy PXE able using options provided by client request.

Please note that you are the second person asking for this feature, so I will have to do it at some point since its now the new way to boot over PXE.

**Comment by sgaosdgr** [comment]
Thanks for looking into this issue.

On the machine to be installed,  UEFI http boot requires HTTPS instead of HTTP for secure connection. Tried creating and installing self signed ssl certificate, but the machine is not able to download ipxe boot image. Likely the certificate failed to pass issuer validation.  Searched BIOS and did not find any setting to force using http instead of https for UEFI http boot.

For using non-encrypted http, the boot screen displays:
```
Error: Access forbidden. Only HTTPS connection is allowed. 
```

Given the extra effort needed to make UEFI http boot working, pxe boot is way easier to set up.

**Comment by sgaosdgr** [comment]
atftp probably works in the majority cases.  However, in this case, the management node has a bonding interface of two 10G NICs, which can be a compatibility issue for atftp.  For the now, the solution/fix for RHEL 9 distros is replacing atftp with tftp-server (the RHEL 9 stock package). 

To replace atftp with tftp-server, add following variables to playbook:
```
vars:
        pxe_stack_tftp_package: tftp-server
        pxe_stack_tftp_service: tftp
```

Another impact is  that after the installation with atftp the compute node could not configure X710 NIC device and bring it up.  

After switching to tftp-sever, the same node installation is fast and successfully completed, ie X710 NIC interface is up running with the assigned ip address,  from the management node, user can ssh into the node as bluebanquise. 

Maybe for RHEL distros, the default tftp server package should switch to tftp-server.

**Comment by oxedions** [comment]
Dear @sgaosdgr 

Many thanks for this feedback. I was surprised by this simple replacement for tftp server on RHEL, but indeed, it seems RedHat improved their tftp server (previously, it was based on xinetd and was a pain to handle).

I will patch the code to use tftp-server from RHEL when using pxe_stack on RHEL 8 or 9. This will allow me to no more have to build atftp since Ubuntu and Debian do not use it, and SLES already provides it natively.

Many thanks for all of these tests :wink:

**Comment by oxedions** [comment]
This issue is now fixed.

**Comment by sgaosdgr** [comment]
Thank you for a very quick fix.

Simon

**Comment by sgaosdgr** [comment]
I think the issue with atftp is with how bonding interface is configured.  I just realized the management node has balance-rr bonding method instead of 802.3ad (dynamic lacp).  However, the native tftp-server works equally well in either case. So tftp-server still wins.
