### ISSUE TITLE
BB-20 - [FEATURE REQUEST] bluebanquise user UID/GID should be a variable

### ISSUE THREAD

**Issue by michaelhoehl** [bluebanquise/bluebanquise#872]
Dear,

the bluebanquise user needs adjustable values for the UID/GID. Per default it uses the UID "1000" as first user after the deployment, but if the customer has an ldap configuration and starts the UID with 1000 as well, then we have duplicates. So it would be better to have at least the option to set a different UID/GID for the bluebanquise user.

Thanks and regards,
Michael

**Comment by oxedions** [comment]
Dear @michaelhoehl 

Thank you for opening this request :blush: 
Its a fair request, and it should be quick to implement. I will work on that.

**Comment by oxedions** [comment]
PR #873 is merged into master, this feature should be added. Please wait few days, I need to validate it in my infra now that its in master.

**Comment by oxedions** [comment]
It works on RHEL, but not on Ubuntu. Curtin does not allow to set a user uid/gid, and late commands happen BEFORE the user defined in curtin is created, so you cannot usermod/groupmod it. This is stupid, I will fix it by creating the user manually in late commands part instead of using curtin for that.

So for RHEL users, master branch is ok, you can now set UID/GID of the bluebanquise user at PXE.
